Repository ARMmbed/DAPLink, pull requests merged in 2019-02, with the labels that each got.

#569 Edit USERS-GUIDE.md
  docs/USERS-GUIDE.md
Labels: docs, in progress

#558 Add boards for mtb accono acn52832, stm32l475 and stm32f439
  projects.yaml
  records/board/mtb_aconno_acn52832.yaml
  records/board/mtb_stm32f439.yaml
  records/board/mtb_stm32l475.yaml
  source/board/mtb_aconno_acn52832.c
  source/board/mtb_stm32f439.c
  source/board/mtb_stm32l475.c
  source/target/st/stm32l4xx_1024/flash_blob.c
  source/target/st/stm32l4xx_1024/target.c
  test/info.py
Labels: in progress

#574 Change default rom settings auto_rst to 1.
  source/daplink/settings/settings_rom.c
Labels: in progress

#535 Adding Wio 3G and BG96
  projects.yaml
  records/board/wio3g.yaml
  records/board/wiobg96.yaml
  source/board/wio3g.c
  source/board/wiobg96.c
  source/target/st/stm32f439zi/target_reset_f439.c
  test/info.py
Labels: in progress

#401 VFS/VBR/FAT Boot Sector Signature + Bootstrap Code / Android USB OTG FIX
  source/daplink/drag-n-drop/virtual_fs.c
Labels: backlog

#570 Wait for buffer status on lpc11u35 EP read
  source/hic_hal/nxp/lpc11u35/usbd_LPC11Uxx.c
Labels: in progress

#587 Added page erase and under reset connection to wise-1570
  source/board/mtb_wise1570.c
  test/info.py
Labels: in progress

#589 Added maxim binary to release, format board ids, added missing boards...
  test/info.py
Labels: in progress

#592 Revert masking of interrupts after flash algo function execute
  source/daplink/interface/swd_host.c
Labels: in progress

#591 Test order: load interface before bootloader.
  test/run_test.py
Labels: in progress
