Repository ARMmbed/DAPLink, pull requests merged in 2022-01, with the labels that each got.

#917 Fix HID interface of LPC55xx HIC
  source/hic_hal/nxp/lpc55xx/usbd_LPC55xx.c
Labels: bug, hic

#918 Fix for i.MXRT10xx Flash Algorithms
  source/family/freescale/mimxrt1020_spi_flash/flash_blob.c
  source/family/freescale/mimxrt1050_hyper_flash/flash_blob.c
  source/family/freescale/mimxrt1050_spi_flash/flash_blob.c
  source/family/freescale/target_reset_mimxrt.c
  source/family/nxp/mimxrt1060_spi_flash/flash_blob.c
  test/info.py
  tools/generate_flash_algo.py
Labels: bug, targets

#923 Remove k20dx_mimxrt1050_evk_hyper_if project
  projects.yaml
  records/board/mimxrt1050_evk_qspi.yaml
  source/family/freescale/mimxrt1050_spi_flash/flash_blob.c
  source/family/freescale/mimxrt1050_spi_flash/target.c
  test/info.py
Labels: targets

#928 microbitv2_bl: Add non-zero board ID to micro:bit DAPLink bootloader.
  source/board/kl27z_microbit_bl.c
  source/board/nrf52820_microbit_bl.c
Labels: enhancement, hic

#927 A few fixes for LPC55xx HIC
  docs/hic/README.md
  docs/hic/lpc55xx.md
  projects.yaml
  records/board/lpc55s69_nrf52840dk.yaml
  records/hic_hal/lpc55s69.yaml
  source/board/lpc55s69_nrf52840dk.c
  source/hic_hal/nxp/lpc55xx/hic_init.c
  source/hic_hal/nxp/lpc55xx/uart.c
  test/info.py
  tools/progen_compile.py
Labels: bug, hic
